# Generated by Django 5.2.5 on 2025-09-23 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_like_view_count_viewcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='view_count',
        ),
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
