# Generated by Django 5.2.5 on 2025-09-29 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_like_view_count_video_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='original_file',
            field=models.FileField(default='', upload_to='uploads/originals/'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VideoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution', models.CharField(max_length=10)),
                ('file', models.FileField(upload_to='uploads/videos/')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='videos.video')),
            ],
        ),
    ]
