# Generated by Django 5.2.5 on 2025-09-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_remove_video_video_file_video_original_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
